### ISSUE TITLE
Potential Talk Ideas

### ISSUE THREAD

**Issue by cmgriffing** [seattlerust/meetups#2]
Hi all,

I have 2 ideas for Rust talks.

My first thought is to do a talk about concurrency. I am not entirely experienced with Rust and concurrency within it, but since I am planning on doing a full bout of research for myself, I would be happy to compose my findings into a set of slides for others to learn from as well.

My second idea for a talk is to talk about my impressions of Rust for building a simple web API coming from a Node.js background. The gist is that I have a simple Node.js API that I have ported over to Rust and Go. I am planning on also trying Elixir and server-side Swift. Eventually, I would like to stand them all up behind a load balancer with them sharing a Redis instance and see if there are any useful performance metrics to use comparatively. The main metrics that come to mind would be I/O, cpu usage, and memory footprint. I have also been tracking my time invested into learning each language as I make each port and I think that could be a useful metric as well. I am open to trying to track other metrics as well.

I would likely not be ready for either of these talks until the August meetup.

Do either of these sound interesting? I would be happy to give both talks, but not at the same meetup. :P

Thanks.

**Comment by sbeckeriv** [comment]
I would be excited for both! I am excited about rust's concurrency story and the web services are more likely going to be a practical use for me in the future. 

I also love the idea of pull request for topics. Please plan for august. @pnathan or @ranweiler can yell at me later if there is something else planned. 

Thanks again!
Becker

**Comment by cmgriffing** [comment]
I meant to reply sooner. I will get started on an outline of what I intend to cover for Concurrency and I will make another comment with a link when I have that ready to review.

I will postpone a web services talk until I have more code and info to go on for that and I will create a new  Issue/PR when that is ready.

**Comment by pnathan** [comment]
Hi everyone! There was a bit of a mixup and two seattle rust github organizations exist!  I got distracted by the metaphorical squirrel and didn't close this organization down....

https://github.com/seattlers/meetups is the other one; that one is the one which is driving http://seattle.rs.

These ideas sound amazing!  I fully support them!

**Comment by cmgriffing** [comment]
I will create a new issue over on that repo for feedback on my outline structure when that is ready. After that, when my talk slides are ready, I will create a pull request over there as well.

Thanks again.
